---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"
inputs:
- name: cfenv-springboot
outputs:
- name: jar
run:
  path: sh
  args:
  - -exc
  - |
    curl -L -o gradle.zip "https://services.gradle.org/distributions/gradle-2.12-bin.zip"
    unzip gradle.zip
    cd cfenv-springboot && ../gradle-2.12/bin/gradle build -Pversion=$(git describe --always) --console plain
    cp build/libs/cfenv-springboot-$(git describe --always).jar ../jar/cfenv-springboot.jar

