---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"
run:
  path: sh
  args:
  - -exc
  - |
    sudo apt-get install gradle
    cd cfenv-springboot && gradle build
