---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"
run:
  path: sh
  args:
  - -exc
  - |
    curl -L -o gradle.zip "https://services.gradle.org/distributions/gradle-2.12-bin.zip"
    unzip gradle.zip
    cd cfenv-springboot && ../gradle-2.12/bin/gradle build
